###
GET http://localhost:8081/api/periods
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjEyNTk0ODYsImV4cCI6MTY2MTM0NTg4Nn0.Ee9og0nGRJApncc708gdFadaHVyed5sDfRtTGNhTRbw


###
GET http://localhost:8081/api/periods/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjEyNTk0ODYsImV4cCI6MTY2MTM0NTg4Nn0.Ee9og0nGRJApncc708gdFadaHVyed5sDfRtTGNhTRbw

###
POST http://localhost:8081/api/periods 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjEyNTk0ODYsImV4cCI6MTY2MTM0NTg4Nn0.Ee9og0nGRJApncc708gdFadaHVyed5sDfRtTGNhTRbw

{
  "id": 375,
  "type": "No flows",
  "date": "2022-08-19"
}


###
PATCH http://localhost:8081/api/periods/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjEyNTk0ODYsImV4cCI6MTY2MTM0NTg4Nn0.Ee9og0nGRJApncc708gdFadaHVyed5sDfRtTGNhTRbw

{
  "type": "Breast pain",
  "date": "1999-08-19"
}



###

POST http://localhost:8081/api/registration 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjEyNTk0ODYsImV4cCI6MTY2MTM0NTg4Nn0.Ee9og0nGRJApncc708gdFadaHVyed5sDfRtTGNhTRbw

{"login": "user22","password": "user22"}

###

POST http://localhost:8081/api/authentication 
Content-Type: application/json

{"login": "user22","password": "user22"}



###
GET http://localhost:8081/api/refresh
