###
GET http://localhost:8081/api/periods

###
GET http://localhost:8081/api/periods/4

###
POST http://localhost:8081/api/periods 
Content-Type: application/json

{
  "id": 356,
  "type": "No flows",
  "date": "2022-08-19"
}

###

POST http://localhost:8081/registration 
Content-Type: application/json

{"login": "login2","password": "nonHashedPassword2"}


###
PATCH http://localhost:8081/api/periods/1
Content-Type: application/json

{
  "type": "Breast pain",
  "date": "1999-08-19"
}