###
GET http://localhost:8081/api/periods
Authorization: Bearer 

###
GET http://localhost:8081/api/periods/4
Authorization: Bearer 


###
POST http://localhost:8081/api/periods 
Content-Type: application/json
Authorization: Bearer 

{
  "id": 378,
  "type": "No flows",
  "date": "2022-08-19"
}


###
PATCH http://localhost:8081/api/periods/6
Content-Type: application/json
Authorization: Bearer 

{
  "type": "Breast pain",
  "date": "1999-08-19"
}



###

POST http://localhost:8081/api/registration 
Content-Type: application/json

{"login": "user24","password": "user24"}

###

POST http://localhost:8081/api/authentication 
Content-Type: application/json

{"login": "user24","password": "user24"}



